#!/usr/bin/env bash
# Configure Nginx with a custom HTTP header X-Served-By containing hostname

# Update package lists
apt-get -y update

# Install nginx
apt-get -y install nginx

# Create a Hello World page
echo "Hello World!" > /var/www/html/index.html

# Add custom header configuration to Nginx
header_config="server_name _;\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/server_name _;/$header_config/" /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
