#!/usr/bin/env bash

# Update package lists
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Ensure Nginx is running
service nginx start

# Configure Nginx to return 'Holberton School' on root request
echo 'Holberton School for the win!' > /var/www/html/index.html

# Allow traffic on port 80
ufw allow 80/tcp

# Restart Nginx without systemctl
kill -HUP $(cat /var/run/nginx.pid)
