#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

apt-get update -y
apt-get install nginx -y
service nginx start
echo 'Holberton School' | > /var/www/html/index.html
ufw allow 80/tcp


