#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

# Update package lists
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Ensure Nginx is running
service nginx start

# Allow traffic on port 80
ufw allow 80/tcp

# Configure redirection
sed -i '/server_name _;/a \
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
nginx -s reload

